Expand aliases in shell script system_test.sh
eradman/entr pull request #149
Opened 2024-08-23 20:37 UTC by ottok

By default shell/bash does not use aliases. This can be verified by running 'alias' after any alias setting commands, and see that it is empty.

Activate shell option expand_aliases for the following alias lines to work correctly.

2024-08-23 22:00 UTC, eradman requested changes
Unfortunately `shopt` does not appear to be a builtin for `zsh`, `ksh`, and `ash`.

2024-08-23 22:41 UTC, ottok commented
Let me update the PR, I have an idea

2024-08-24 01:03 UTC, ottok commented
Tested syntax with:

```shell
#!/bin/sh

alias atest='echo works'

# Bourne Again Shell (bash)
command -v shopt > /dev/null && shopt -s expand_aliases

# POSIX shell (sh), Debian Almquist Shell (dash)
#set -e

# Korn Shell (ksh)
#set -a

# Z Shell (zsh)
#setopt alias_expansion

atest
```

Example output:
```
for x in sh dash bash ksh zsh; do echo "----------------"; echo "$x:"; $x -c ./test.sh; done
----------------
sh:
works
----------------
dash:
works
----------------
bash:
works
----------------
ksh:
works
----------------
zsh:
works
```

2024-08-24 01:31 UTC, eradman approved these changes
This works! Tested both non-interactive and interactive with `ksh` and `bash`.
System tests pass with `zsh` (Mac OS) and `ash` (Alpine Linux)

2024-08-24 01:31 UTC, merged